package app.eluvio.mobile.navigation

import androidx.navigation3.runtime.NavEntry
import androidx.navigation3.runtime.NavKey
import androidx.navigation3.runtime.entryProvider
import app.eluvio.mobile.screens.discover.DiscoverScreen
import app.eluvio.mobile.screens.myitems.MyItemsScreen
import app.eluvio.mobile.screens.profile.ProfileScreen
import app.eluvio.mobile.screens.property.PropertyDetailScreen
import app.eluvio.mobile.screens.signin.SignInScreen
import app.eluvio.mobile.screens.signin.mobileSignInEntry
import app.eluvio.mobile.screens.videoplayer.VideoPlayerScreen
import app.eluvio.mobile.screens.videoplayer.mobileVideoPlayerEntry
import app.eluvio.wallet.navigation.NavigationEvent
import app.eluvio.wallet.screens.property.PropertyDetailNavArgs
import app.eluvio.wallet.screens.property.propertyDetailEntry
import app.eluvio.wallet.screens.signin.SignInNavArgs
import app.eluvio.wallet.screens.videoplayer.VideoPlayerArgs
import kotlinx.serialization.Serializable

/**
 * Top-level tab routes. The screen-specific routes (sign-in, property detail, video player)
 * reuse the shared `*NavArgs` classes from :core directly, so both apps share the same wire
 * format.
 */
@Serializable
data object DiscoverRoute : NavKey

@Serializable
data object MyItemsRoute : NavKey

@Serializable
data object ProfileRoute : NavKey

/**
 * Wires every destination into [androidx.navigation3.ui.NavDisplay]. Tab roots get raw
 * `entry<T>` since their VMs don't take a NavKey; detail screens use the `<vm>Entry` helpers
 * generated by `nav3-hilt-vm`. Each entry body delegates to the VM-bound overload of its screen
 * composable (e.g. `DiscoverScreen()` / `PropertyDetailScreen(vm)`), which lives alongside the
 * stateless screen in the feature package — this file is just the registry. Navigation events
 * bubble up through `LocalNavigator`, so the entry bodies don't reach for a NavController.
 */
fun mobileEntryProvider(): (NavKey) -> NavEntry<NavKey> =
    entryProvider {
        entry<DiscoverRoute> { DiscoverScreen() }
        entry<MyItemsRoute> { MyItemsScreen() }
        entry<ProfileRoute> { ProfileScreen() }
        // Sign-in renders translucent on top of the previous entry — see SignInScreen.
        mobileSignInEntry(metadata = FadeDialogSceneStrategy.fullScreenDialog()) { vm ->
            SignInScreen(vm)
        }
        propertyDetailEntry { vm -> PropertyDetailScreen(vm) }
        mobileVideoPlayerEntry { vm -> VideoPlayerScreen(vm) }
    }

/**
 * Mobile-side resolution of the shared [NavigationEvent] vocabulary into a mutation of
 * [MobileNavigationState]. Installed once at the activity level via `LocalNavigator provides …`.
 * Returns silently for events that have no mobile equivalent yet — those fall through to a toast
 * during dev rather than silently dropping.
 */
internal fun MobileNavigationState.handleMobileNavEvent(
    event: NavigationEvent,
    onUnhandled: () -> Unit,
) {
    when (event) {
        NavigationEvent.GoBack -> {
            // Pop the current tab; if it's already at root and not on the start tab, switch back
            // to the start tab (matches Nav 2's `popUpTo(startDestinationId) { saveState=true }`).
            val active = backStacks[topLevelRoute] ?: return
            if (active.size > 1) {
                active.removeLastOrNull()
            } else if (topLevelRoute != startRoute) {
                topLevelRoute = startRoute
            }
            // else: at root of start tab — let NavDisplay's default onBack finish the activity.
        }

        is NavigationEvent.Push -> {
            val route = event.target.toMobileRoute() ?: return onUnhandled()
            backStacks[topLevelRoute]?.add(route)
        }

        is NavigationEvent.Replace -> {
            val route = event.target.toMobileRoute() ?: return onUnhandled()
            val stack = backStacks[topLevelRoute] ?: return
            stack.removeLastOrNull()
            stack.add(route)
        }

        is NavigationEvent.SetRoot -> {
            val route = event.target.toMobileRoute() ?: return onUnhandled()
            // Reset to the start tab and pin the new route as its only entry.
            val startStack = backStacks[startRoute] ?: return
            while (startStack.size > 1) startStack.removeAt(startStack.lastIndex)
            startStack.removeAt(0)
            startStack.add(route)
            topLevelRoute = startRoute
        }
    }
}

/**
 * Allowlist of routes mobile can render today. Returns the route itself if supported, or null —
 * unsupported routes fall through to a toast so they're visible during dev rather than silently
 * dropped.
 */
private fun NavKey.toMobileRoute(): NavKey? = when (this) {
    is SignInNavArgs, is PropertyDetailNavArgs, is VideoPlayerArgs -> this
    else -> null
}
