package app.eluvio.mobile.navigation

import android.widget.Toast
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.ui.platform.LocalContext
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.navigation3.runtime.NavEntry
import androidx.navigation3.runtime.NavKey
import androidx.navigation3.runtime.entryProvider
import app.eluvio.mobile.screens.discover.DiscoverScreen
import app.eluvio.mobile.screens.myitems.MyItemsScreen
import app.eluvio.mobile.screens.profile.ProfileScreen
import app.eluvio.mobile.screens.profile.launchEnvSwitcherIfDebug
import app.eluvio.mobile.screens.profile.rememberNetworkRowTapper
import app.eluvio.mobile.screens.property.PropertyDetailScreen
import app.eluvio.mobile.screens.signin.MobileSignInViewModel
import app.eluvio.mobile.screens.signin.SignInScreen
import app.eluvio.mobile.screens.signin.mobileSignInEntry
import app.eluvio.mobile.screens.videoplayer.MobileVideoPlayerViewModel
import app.eluvio.mobile.screens.videoplayer.VideoPlayerScreen
import app.eluvio.mobile.screens.videoplayer.mobileVideoPlayerEntry
import app.eluvio.wallet.navigation.LocalNavigator
import app.eluvio.wallet.navigation.NavigationEvent
import app.eluvio.wallet.navigation.asPush
import app.eluvio.wallet.navigation.onClickTarget
import app.eluvio.wallet.screens.dashboard.discover.DiscoverViewModel
import app.eluvio.wallet.screens.dashboard.profile.ProfileViewModel
import app.eluvio.wallet.screens.property.DynamicPageLayoutState.CarouselItem
import app.eluvio.wallet.screens.property.PropertyDetailNavArgs
import app.eluvio.wallet.screens.property.PropertyDetailViewModel
import app.eluvio.wallet.screens.property.propertyDetailEntry
import app.eluvio.wallet.screens.signin.SignInNavArgs
import app.eluvio.wallet.screens.videoplayer.VideoPlayerArgs
import app.eluvio.wallet.util.subscribeToState
import io.reactivex.rxjava3.disposables.CompositeDisposable
import io.reactivex.rxjava3.kotlin.addTo
import io.reactivex.rxjava3.kotlin.subscribeBy
import kotlinx.serialization.Serializable

/**
 * Top-level tab routes. The screen-specific routes (sign-in, property detail, video player)
 * reuse the shared `*NavArgs` classes from :core directly, so both apps share the same wire
 * format.
 */
@Serializable
data object DiscoverRoute : NavKey

@Serializable
data object MyItemsRoute : NavKey

@Serializable
data object ProfileRoute : NavKey

/**
 * Wires every destination into [androidx.navigation3.ui.NavDisplay]. Tab roots get raw
 * `entry<T>` since their VMs don't take a NavKey; detail screens use the `<vm>Entry` helpers
 * generated by `nav3-hilt-vm`. Navigation events bubble up through `LocalNavigator`, so the
 * entry bodies don't reach for a NavController.
 */
fun mobileEntryProvider(): (NavKey) -> NavEntry<NavKey> =
    entryProvider {
        entry<DiscoverRoute> { DiscoverNavScreen() }
        entry<MyItemsRoute> { MyItemsScreen() }
        entry<ProfileRoute> { ProfileNavScreen() }
        // Sign-in renders translucent on top of the previous entry — see SignInScreen.
        mobileSignInEntry(metadata = FadeDialogSceneStrategy.fullScreenDialog()) { vm ->
            SignInNavScreen(vm)
        }
        propertyDetailEntry { vm -> PropertyDetailNavScreen(vm) }
        mobileVideoPlayerEntry { vm -> VideoPlayerNavScreen(vm) }
    }

@Composable
private fun DiscoverNavScreen() {
    val vm: DiscoverViewModel = hiltViewModel()
    vm.subscribeToState { _, state ->
        DiscoverScreen(state = state, onPropertyClick = vm::onPropertyClicked, onRetry = vm::retry)
    }
}

@Composable
private fun ProfileNavScreen() {
    val vm: ProfileViewModel = hiltViewModel()
    val tapper = rememberNetworkRowTapper()
    val context = LocalContext.current
    vm.subscribeToState { _, state ->
        ProfileScreen(
            state = state,
            onSignOut = vm::signOut,
            onNetworkRowTap = { if (tapper.tap()) context.launchEnvSwitcherIfDebug() },
        )
    }
}

@Composable
private fun SignInNavScreen(vm: MobileSignInViewModel) {
    vm.subscribeToState { _, state ->
        SignInScreen(
            signInUrl = state.signInUrl,
            loadingContent = state.loadingContent,
            onAuthCaptured = vm::onAuthCaptured,
            onAuthTabDismissed = vm::onAuthTabDismissed,
        )
    }
}

@Composable
private fun PropertyDetailNavScreen(vm: PropertyDetailViewModel) {
    val context = LocalContext.current
    vm.subscribeToState { _, state ->
        PropertyDetailScreen(
            state = state,
            onItemClick = { item ->
                val real = (item as? CarouselItem.BannerWrapper)?.delegate ?: item
                if (real !is CarouselItem.Media) {
                    Toast.makeText(context, "Not supported yet: $real", Toast.LENGTH_SHORT).show()
                    return@PropertyDetailScreen
                }
                when (val target = real.entity.onClickTarget(real.permissionContext)) {
                    is VideoPlayerArgs -> vm.navigateTo(target.asPush())
                    null -> Toast.makeText(context, "No access to this item", Toast.LENGTH_SHORT)
                        .show()

                    else -> Toast.makeText(
                        context,
                        "Not supported yet: $target",
                        Toast.LENGTH_SHORT
                    )
                        .show()
                }
            },
            onNavigateUp = { vm.navigateTo(NavigationEvent.GoBack) },
        )
    }
}

@Composable
private fun VideoPlayerNavScreen(vm: MobileVideoPlayerViewModel) {
    val context = LocalContext.current
    // MobileVideoPlayerViewModel extends ViewModel directly (not BaseViewModel) since the
    // player itself is the "state" — so no subscribeToState here. We tap LocalNavigator
    // directly for the back navigation on load errors.
    val navigator = LocalNavigator.current
    DisposableEffect(vm) {
        val listener = object : Player.Listener {
            override fun onPlayerError(error: PlaybackException) {
                app.eluvio.wallet.util.logging.Log.e(
                    "Error playing video ${error.errorCodeName}", error
                )
            }
        }
        vm.exoPlayer.addListener(listener)
        val disposables = CompositeDisposable()
        vm.loadErrors.subscribeBy {
            Toast.makeText(context, "Error loading video. Try again later.", Toast.LENGTH_SHORT)
                .show()
            navigator(NavigationEvent.GoBack)
        }.addTo(disposables)
        onDispose {
            vm.exoPlayer.removeListener(listener)
            disposables.clear()
        }
    }
    VideoPlayerScreen(player = vm.exoPlayer)
}

/**
 * Mobile-side resolution of the shared [NavigationEvent] vocabulary into a mutation of
 * [MobileNavigationState]. Installed once at the activity level via `LocalNavigator provides …`.
 * Returns silently for events that have no mobile equivalent yet — those fall through to a toast
 * during dev rather than silently dropping.
 */
internal fun MobileNavigationState.handleMobileNavEvent(
    event: NavigationEvent,
    onUnhandled: () -> Unit,
) {
    when (event) {
        NavigationEvent.GoBack -> {
            // Pop the current tab; if it's already at root and not on the start tab, switch back
            // to the start tab (matches Nav 2's `popUpTo(startDestinationId) { saveState=true }`).
            val active = backStacks[topLevelRoute] ?: return
            if (active.size > 1) {
                active.removeLastOrNull()
            } else if (topLevelRoute != startRoute) {
                topLevelRoute = startRoute
            }
            // else: at root of start tab — let NavDisplay's default onBack finish the activity.
        }

        is NavigationEvent.Push -> {
            val route = event.target.toMobileRoute() ?: return onUnhandled()
            backStacks[topLevelRoute]?.add(route)
        }

        is NavigationEvent.Replace -> {
            val route = event.target.toMobileRoute() ?: return onUnhandled()
            val stack = backStacks[topLevelRoute] ?: return
            stack.removeLastOrNull()
            stack.add(route)
        }

        is NavigationEvent.SetRoot -> {
            val route = event.target.toMobileRoute() ?: return onUnhandled()
            // Reset to the start tab and pin the new route as its only entry.
            val startStack = backStacks[startRoute] ?: return
            while (startStack.size > 1) startStack.removeAt(startStack.lastIndex)
            startStack.removeAt(0)
            startStack.add(route)
            topLevelRoute = startRoute
        }
    }
}

/**
 * Allowlist of routes mobile can render today. Returns the route itself if supported, or null —
 * unsupported routes fall through to a toast so they're visible during dev rather than silently
 * dropped.
 */
private fun NavKey.toMobileRoute(): NavKey? = when (this) {
    is SignInNavArgs, is PropertyDetailNavArgs, is VideoPlayerArgs -> this
    else -> null
}
