[versions]
agp = "8.1.0-beta03"
compose-bom = "2023.05.01"
hilt-android = "2.44"
hilt-navigation-compose = "1.0.0"
lifecycle-viewmodel-ktx = "2.6.1"
navigation-compose = "2.5.3"
org-jetbrains-kotlin-android = "1.8.21"
core-ktx = "1.10.1"
leanback = "1.0.0"
androidx-activity-compose = "1.7.1"
compose-tv = "1.0.0-alpha06"
retrofit = "2.9.0"
hilt = "2.46.1"
runtime-rxjava3 = "1.4.3"
rxandroid = "3.0.2"
rxjava = "3.1.5"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-rxjava3 = { module = "androidx.compose.runtime:runtime-rxjava3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-tv-foundation = { module = "androidx.tv:tv-foundation", version.ref = "compose-tv" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "compose-tv" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]

