package app.eluvio.wallet.navigation

import androidx.compose.animation.EnterTransition
import androidx.compose.animation.ExitTransition
import androidx.compose.animation.togetherWith
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.window.DialogProperties
import androidx.lifecycle.viewmodel.navigation3.rememberViewModelStoreNavEntryDecorator
import androidx.navigation3.runtime.NavBackStack
import androidx.navigation3.runtime.NavKey
import androidx.navigation3.runtime.entryProvider
import androidx.navigation3.runtime.rememberSaveableStateHolderNavEntryDecorator
import androidx.navigation3.scene.DialogSceneStrategy
import androidx.navigation3.ui.NavDisplay
import app.eluvio.wallet.screens.dashboard.Dashboard
import app.eluvio.wallet.screens.dashboard.DashboardNavArgs
import app.eluvio.wallet.screens.deeplink.NftClaim
import app.eluvio.wallet.screens.deeplink.nftClaimEntry
import app.eluvio.wallet.screens.gallery.ImageGallery
import app.eluvio.wallet.screens.gallery.imageGalleryEntry
import app.eluvio.wallet.screens.home.Home
import app.eluvio.wallet.screens.home.homeEntry
import app.eluvio.wallet.screens.nftdetail.NftDetail
import app.eluvio.wallet.screens.nftdetail.legacy.LegacyNftDetail
import app.eluvio.wallet.screens.nftdetail.legacy.LockedMediaDialog
import app.eluvio.wallet.screens.nftdetail.legacy.LockedMediaDialogNavArgs
import app.eluvio.wallet.screens.nftdetail.legacy.legacyNftDetailEntry
import app.eluvio.wallet.screens.nftdetail.nftDetailEntry
import app.eluvio.wallet.screens.property.PropertyDetail
import app.eluvio.wallet.screens.property.mediagrid.MediaGrid
import app.eluvio.wallet.screens.property.mediagrid.mediaGridEntry
import app.eluvio.wallet.screens.property.propertyDetailEntry
import app.eluvio.wallet.screens.property.search.PropertySearch
import app.eluvio.wallet.screens.property.search.propertySearchEntry
import app.eluvio.wallet.screens.property.upcoming.UpcomingVideo
import app.eluvio.wallet.screens.property.upcoming.upcomingVideoEntry
import app.eluvio.wallet.screens.purchaseprompt.PurchasePrompt
import app.eluvio.wallet.screens.purchaseprompt.purchasePromptEntry
import app.eluvio.wallet.screens.qrdialogs.externalmedia.ExternalMediaQrDialog
import app.eluvio.wallet.screens.qrdialogs.externalmedia.externalMediaQrDialogEntry
import app.eluvio.wallet.screens.qrdialogs.fulfillment.FulfillmentQrDialog
import app.eluvio.wallet.screens.qrdialogs.fulfillment.fulfillmentQrDialogEntry
import app.eluvio.wallet.screens.qrdialogs.generic.FullscreenQRDialog
import app.eluvio.wallet.screens.qrdialogs.generic.fullscreenQRDialogEntry
import app.eluvio.wallet.screens.redeemdialog.RedeemDialog
import app.eluvio.wallet.screens.redeemdialog.redeemDialogEntry
import app.eluvio.wallet.screens.signin.SignIn
import app.eluvio.wallet.screens.signin.tvSignInEntry

private val FullscreenDialog = DialogSceneStrategy.dialog(
    DialogProperties(usePlatformDefaultWidth = false),
)
private val DefaultDialog = DialogSceneStrategy.dialog()

private val NoTransition = EnterTransition.None togetherWith ExitTransition.None

/**
 * Navigation 3 host. Each screen with a NavKey + ViewModel uses the `<vm>Entry { vm -> Screen(vm) }`
 * helper generated by `nav3-hilt-vm`. Screens without a VM (Dashboard, LockedMediaDialog) use the
 * raw `entry<T>` directly.
 *
 * Dialogs use [DialogSceneStrategy] — entries marked with `DialogSceneStrategy.dialog()` metadata
 * render inside a `Dialog`.
 */
@Composable
fun MainNavHost(
    backStack: NavBackStack<NavKey>,
    modifier: Modifier = Modifier,
) {
    NavDisplay(
        backStack = backStack,
        modifier = modifier,
        onBack = { backStack.removeLastOrNull() },
        entryDecorators = listOf(
            rememberSaveableStateHolderNavEntryDecorator(),
            rememberViewModelStoreNavEntryDecorator(),
        ),
        sceneStrategies = listOf(DialogSceneStrategy()),
        // Instant swaps so popUpTo-style replaces don't briefly recompose the outgoing screen
        // against its already-destroyed VM state (e.g. PropertyDetail flashing empty lazy rows
        // during a replace to PurchasePrompt).
        transitionSpec = { NoTransition },
        popTransitionSpec = { NoTransition },
        predictivePopTransitionSpec = { NoTransition },
        entryProvider = entryProvider {
            homeEntry { vm -> Home(vm) }
            entry<DashboardNavArgs> { Dashboard() }

            propertyDetailEntry { vm -> PropertyDetail(vm) }
            mediaGridEntry { vm -> MediaGrid(vm) }
            propertySearchEntry { vm -> PropertySearch(vm) }
            upcomingVideoEntry { vm -> UpcomingVideo(vm) }
            tvSignInEntry { vm -> SignIn(vm) }
            purchasePromptEntry { vm -> PurchasePrompt(vm) }
            nftDetailEntry { vm -> NftDetail(vm) }
            legacyNftDetailEntry { vm -> LegacyNftDetail(vm) }
            imageGalleryEntry { vm -> ImageGallery(vm) }
            nftClaimEntry { vm -> NftClaim(vm) }

            entry<LockedMediaDialogNavArgs>(metadata = { FullscreenDialog }) { args ->
                LockedMediaDialog(args)
            }
            fullscreenQRDialogEntry(metadata = FullscreenDialog) { vm -> FullscreenQRDialog(vm) }
            externalMediaQrDialogEntry(metadata = FullscreenDialog) { vm ->
                ExternalMediaQrDialog(vm)
            }
            fulfillmentQrDialogEntry(metadata = DefaultDialog) { vm ->
                FulfillmentQrDialog(vm)
            }
            redeemDialogEntry(metadata = DefaultDialog) { vm -> RedeemDialog(vm) }

            // VideoPlayerArgs launches VideoPlayerActivity directly — handled in ComposeNavigator.
        },
    )
}
