name: Android CI

on:
  push:
    branches: [ "main" ]
  # Enable manual non-main branch builds from Github
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Secrets File
      run: |
        echo "
        AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
        MUX_ENV_KEY_MAIN=${{ secrets.MUX_ENV_KEY_MAIN }}
        MUX_ENV_KEY_DEMO=${{ secrets.MUX_ENV_KEY_DEMO }}
        " > secrets/secrets.properties

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{ github.workspace }}/keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew assembleDefaultDebug assembleDefaultRelease \
          -Pci_build_number=${{ github.run_number }} \
          -Pandroid.injected.signing.store.file='${{ github.workspace }}/keystore.jks' \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_PASSWORD }}

    - name: Save version info
      run: |
        sha=$(git rev-parse --short ${{ github.sha }})
        app_version=$(./gradlew -q printVersion -Pci_build_number=${{ github.run_number }})
        apk_version=$(echo "$app_version-$sha")
        echo "APK_VERSION=$apk_version" >> $GITHUB_ENV

    - name: Rename APKs
      run: |
        mv app/build/outputs/apk/default/debug/app-default-debug.apk media-wallet-debug-${{ env.APK_VERSION }}.apk
        mv app/build/outputs/apk/default/release/app-default-release.apk media-wallet-release-${{ env.APK_VERSION }}.apk

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: APKs (${{ env.APK_VERSION }})
        path: media-wallet-*.apk
